const internshipDetailData = {
  internships: [
    {
      id: "python-dev",
      title: "Python Developer Internship",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://w7.pngwing.com/pngs/573/501/png-transparent-python-computer-icons-programming-language-font-awesome-github-angle-text-logo.png",
      months: [
        {
          month: 2,
          heading: "Core Python Foundations",
          goals: [
            "Build strong Python basics",
            "Understand syntax, data types and logic",
          ],
          tasks: [
            "Small programs (calculator & pattern printer)",
            "Daily practice with challenges (HackerRank & LeetCode Easy)",
          ],
          topicsCovered: [
            "Python setup, IDEs (VS Code, Jupyter & PyCharm)",
            "Operators and Expressions",
            "Variables, Data Types, Typecasting",
            "String operations and formatting",
            "Control Structures: if, else, elif",
            "Functions and Scope",
            "Lists, Tuples, Sets, Dictionaries",
            "Basic error handling (try–except)",
            "File I/O",
            "HTML Basics",
            "Regex Function",
            "Loops: for, while",
            "Tkinter Basics",
          ],
        },
        {
          month: 4,
          heading: "OBJECT-ORIENTED Programming + Intermediate Python",
          goals: ["Understand OOP and intermediate programming concepts"],
          tasks: [
            "Build a Contact Book or Library Management",
            "Fetch data using APIs (like Weather API)",
            "Basic unit testing with unittest",
            "Tic Tac Toe using Python",
          ],
          topicsCovered: [
            "OOP Concepts: Class, Object, Inheritance, Polymorphism",
            "Lambda, map(), filter(), zip(), enumerate()",
            "Variables, Data Types, Typecasting",
            "Exception handling (custom exceptions)",
            "Modules & Packages (import, pip)",
            "List/Dict Comprehensions",
            "Working with JSON and APIs",
          ],
        },
        {
          month: 6,
          heading: "Real-World Projects + Tools",
          goals: [
            "Apply concepts in real-world mini projects",
            "Learn essential Python libraries",
          ],
          tasks: [
            "Expense Tracker with GUI",
            "Weather App (API + Tkinter)",
            "Blog API with Flask",
            "Data Visualizer using pandas + matplotlib",
            "Developing a website similar Unacademy.",
          ],
          topicsCovered: [
            "Pandas, matplotlib, numpy for data",
            "Introduction to framework - DJANGO",
            "Git/GitHub basics",
            "Intro to databases with Postgresql or MySQL connector",
          ],
        },
      ],
    },
    {
      id: "mern-stack",
      title: "MERN Stack Developer Internship",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://www.pngfind.com/pngs/m/415-4152510_web-development-icon-png-clipart-website-development-programming.png",
      months: [
        {
          month: 2,
          heading: "Web Development Fundamentals & Advanced JavaScript",
          goals: [
            "Build a strong foundation in front-end web technologies.",
            "Master core JavaScript concepts before moving to React.",
          ],
          tasks: [
            "Build a personal portfolio web page.",
            "Create responsive web layouts using HTML & CSS.",
            "Build a weather app using JavaScript and OpenWeather API.",
            "Complete weekly JavaScript coding challenges.",
          ],
          topicsCovered: [
            "Introduction to Web Development & Internet Architecture",
            "HTML5: Structure, Forms, Tables, Semantic Elements",
            "CSS3: Styling, Flexbox, Grid, Animations",
            "Responsive Web Design (Media Queries, Bootstrap)",
            "Introduction to JavaScript (Variables, Loops, Functions)",
            "DOM Manipulation & Events",
            "ES6 Features (Let, Const, Arrow Functions, Template Literals)",
            "Objects, Arrays & JSON",
            "Asynchronous JavaScript (Promises, Async/Await)",
            "Fetch API and AJAX Calls",
            "Error Handling & Debugging",
            "Introduction to APIs",
          ],
        },
        {
          month: 4,
          heading: "React.js Development & Backend with Node.js and Express.js",
          goals: [
            "Learn to build modern, dynamic front-end applications using React.",
            "Understand backend development and server-side programming.",
          ],
          tasks: [
            "Build a 'Task Manager' or 'To-Do' app using React.",
            "Build RESTful APIs for a small application.",
            "Integrate frontend (React) with Express backend.",
            "Handle routing, middleware, and error responses in Express.",
          ],
          topicsCovered: [
            "Introduction to React & JSX",
            "Components, Props & State",
            "Conditional Rendering & Lists",
            "React Hooks (useState, useEffect)",
            "React Router (Navigation & Routing)",
            "Form Handling and Validation",
            "Context API & Basic State Management",
            "Introduction to Node.js & NPM",
            "Setting Up Express.js Server",
            "REST API Development",
            "Middleware, Routing & Error Handling",
            "CRUD Operations with In-Memory Data",
            "File Upload & Static File Handling",
          ],
        },
        {
          month: 6,
          heading: "Database Integration (MongoDB) & Capstone Project",
          goals: [
            "Learn database operations and secure app development.",
            "Develop a full-stack MERN application and deploy it online.",
          ],
          tasks: [
            "Build a 'User Authentication System' (Register, Login, Logout).",
            "Plan front-end and backend architecture for a full-stack project.",
            "Integrate APIs with React frontend and implement authentication.",
            "Host application on Render, Vercel, or MongoDB Atlas.",
            "Present final project with documentation and demo.",
          ],
          topicsCovered: [
            "Introduction to MongoDB & NoSQL Databases",
            "CRUD Operations using Mongoose",
            "Schema & Model Design",
            "Connecting Express.js with MongoDB",
            "User Authentication (JWT & Bcrypt)",
            "Environment Variables and Security Practices",
            "Capstone Project Ideas: E-Commerce Platform, Social Media Web App, Online Course Portal, Blog Management System, Task Tracking Dashboard",
            "Integration of API with React Frontend",
            "Implementation of Authentication and Database Operations",
            "Final Project Presentation & Review",
          ],
        },
      ],
    },
    {
      id: "flutter-ui",
      title: "Flutter Internship",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://img.icons8.com/?size=1200&id=TwdB62yFXesu&format=jpg",
      months: [
        {
          month: 2,
          heading: "Introduction to Flutter, Dart & UI Design",
          goals: [
            "Understand the fundamentals of Flutter and set up the development environment.",
            "Learn to build beautiful and responsive user interfaces using Flutter widgets.",
          ],
          tasks: [
            "Create a simple 'Hello Flutter' app.",
            "Build a calculator app using basic widgets.",
            "Weekly coding challenges.",
            "Build a multi-screen app using navigation.",
            "Design a login and signup screen UI.",
          ],
          topicsCovered: [
            "Introduction to Flutter & cross-platform development.",
            "Installing Flutter SDK, Android Studio / VS Code.",
            "Introduction to Dart programming language.",
            "Variables, data types, and operators in Dart.",
            "Conditional statements and loops.",
            "Functions in Dart.",
            "Flutter architecture overview (Widget tree, hot reload).",
            "Stateless vs Stateful widgets.",
            "Layout widgets: Row, Column, Stack, Container.",
            "Input widgets: TextField, Buttons, Dropdowns, Icons.",
            "Navigation and routes.",
            "Gesture detection & user interaction.",
          ],
        },
        {
          month: 4,
          heading: "State Management, API Integration & Database Storage",
          goals: [
            "Understand state management and connect apps with external data sources.",
            "Learn how to store and manage data locally and with backend databases.",
          ],
          tasks: [
            "Build a 'Notes App' with local storage.",
            "Create a 'To-Do App' using Firebase.",
            "Mini Project: Weather App or News App using public APIs.",
          ],
          topicsCovered: [
            "State management basics (setState, Provider, Riverpod intro).",
            "Asynchronous programming (Futures, async & await).",
            "Fetching data from REST APIs.",
            "JSON parsing in Flutter.",
            "Error handling & loading states.",
            "API integration best practices.",
            "Local storage with SharedPreferences.",
            "SQLite database integration.",
            "Firebase introduction (Firestore database).",
            "CRUD operations (Create, Read, Update, Delete).",
            "Authentication with Firebase (Login / Signup).",
          ],
        },
        {
          month: 6,
          heading: "Advanced Flutter, App Deployment & Capstone Project",
          goals: [
            "Learn to polish, test, and publish mobile apps.",
            "Apply all knowledge to develop a complete, production-ready Flutter app.",
          ],
          tasks: [
            "Add animations and validation to existing projects.",
            "Prepare your app for Play Store upload.",
            "Design app structure and UI.",
            "Integrate database and API.",
            "Implement authentication and state management.",
            "Test and debug the full application.",
            "Final project presentation and review.",
          ],
          topicsCovered: [
            "Animation in Flutter (implicit & explicit animations).",
            "Form validation and input handling.",
            "File handling & image upload.",
            "Push notifications.",
            "Debugging & performance optimization.",
            "Building and releasing Flutter apps (Android & iOS).",
            "Capstone project ideas: E-Commerce App, Food Delivery App, Expense Tracker App, Online Course App, Travel Booking App.",
          ],
        },
      ],
    },
    {
      id: "data-science",
      title: "Data Science",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://cdn-icons-png.flaticon.com/512/2801/2801091.png",
      months: [
        {
          month: 2,
          heading: "Foundation of Data Science",
          goals: [
            "Build a strong foundation in Python programming and data handling.",
            "Develop understanding of data visualization, statistics, and probability.",
          ],
          tasks: [
            "Write Python programs using variables, loops, and functions.",
            "Manipulate and clean datasets using NumPy and Pandas.",
            "Create visualizations with Matplotlib and Seaborn.",
            "Perform exploratory data analysis and generate insights.",
          ],
          topicsCovered: [
            "Python Programming Basics (Variables, Functions, Loops, NumPy, Pandas)",
            "Data Manipulation (Cleaning, Filtering, Merging, Grouping)",
            "Data Visualization (Matplotlib, Seaborn, Storytelling with Data)",
            "Statistics & Probability (Descriptive Stats, Distributions, Sampling, Bayes’ Theorem)",
            "Mini Project: Exploratory Data Analysis & Visual Report",
          ],
        },
        {
          month: 4,
          heading: "Intermediate Concepts & Machine Learning",
          goals: [
            "Understand key machine learning concepts and algorithms.",
            "Apply regression, classification, and clustering techniques on datasets.",
          ],
          tasks: [
            "Implement supervised and unsupervised learning models.",
            "Build and evaluate models using performance metrics.",
            "Apply clustering and dimensionality reduction using K-Means and PCA.",
            "Optimize models using cross-validation and regularization.",
          ],
          topicsCovered: [
            "Introduction to Machine Learning (Supervised & Unsupervised Learning)",
            "Regression & Classification (Linear, Logistic, Decision Trees, Random Forests)",
            "Model Evaluation (Accuracy, Precision, Recall, F1-score, Confusion Matrix)",
            "Clustering & Dimensionality Reduction (K-Means, PCA)",
            "Model Optimization (Cross-Validation, GridSearchCV, Regularization)",
            "Project: Build a Spam Classifier & Customer Segmentation",
          ],
        },
        {
          month: 6,
          heading: "Advanced Topics & Final Project",
          goals: [
            "Master advanced data science topics including time series and deep learning.",
            "Complete a full-scale data science project for deployment and presentation.",
          ],
          tasks: [
            "Analyze time-based data using ARIMA and trend analysis.",
            "Build neural network models using TensorFlow/Keras.",
            "Develop and present a capstone project based on real-world data.",
            "Prepare portfolio-ready GitHub repositories and final certification materials.",
          ],
          topicsCovered: [
            "Time Series Analysis (Trend Analysis, ARIMA, Datetime Handling)",
            "Deep Learning Basics (Neural Networks, TensorFlow/Keras, Image Recognition)",
            "Capstone Project: Sales Forecasting / Sentiment Analysis / Fraud Detection",
            "Presentation & Certification (Demo, Review, Certificate Issuance)",
            "Deliverables: Weekly Tasks, 2 Mini Projects, 1 Final Project, GitHub Portfolio",
          ],
        },
      ],
    },
    {
      id: "cyber-security",
      title: "Cyber Security & Networking",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://www.vhv.rs/dpng/d/126-1268843_cyber-security-cyber-security-icon-png-transparent-png.png",
        months: [
          {
            month: 2,
            heading:
              "Introduction to Cyber Security, Networking & Security Tools",
            goals: [
              "Understand the fundamentals of cybersecurity and computer networking.",
              "Learn how operating systems and tools are used in cybersecurity operations.",
            ],
            tasks: [
              "Identify vulnerabilities in a sample network.",
              "Configure basic network connections.",
              "Weekly quiz on cybersecurity fundamentals.",
              "Perform network scanning using Nmap.",
              "Capture and analyze packets using Wireshark.",
            ],
            topicsCovered: [
              "What is Cyber Security? Importance & Scope.",
              "Types of Cyber Attacks & Threats.",
              "Introduction to Networking (LAN, WAN, VPN).",
              "OSI & TCP/IP Models.",
              "IP Addressing, Subnetting & Ports.",
              "Network Devices: Router, Switch, Firewall.",
              "Basic Linux Commands for Security Professionals.",
              "Windows and Linux Security Essentials.",
              "File System Permissions and Access Controls.",
              "User Authentication and Encryption.",
              "Introduction to Security Tools (Nmap, Wireshark, Metasploit).",
              "Understanding Firewalls, Proxy, and IDS/IPS.",
              "Password Cracking & Hashing Basics.",
            ],
          },
          {
            month: 4,
            heading:
              "Web & Network Security, Ethical Hacking & Penetration Testing",
            goals: [
              "Understand web application vulnerabilities and network defense mechanisms.",
              "Learn ethical hacking techniques and penetration testing methods.",
            ],
            tasks: [
              "Simulate a web vulnerability testing environment and generate a security report.",
              "Perform basic penetration testing on a demo site.",
              "Create vulnerability assessment reports.",
            ],
            topicsCovered: [
              "Web Application Security Overview.",
              "OWASP Top 10 Vulnerabilities.",
              "SQL Injection, Cross-Site Scripting (XSS), CSRF.",
              "Securing APIs and Web Applications.",
              "VPN Configuration and Secure Network Setup.",
              "Email and Cloud Security Fundamentals.",
              "Phases of Ethical Hacking.",
              "Footprinting and Reconnaissance.",
              "Scanning and Enumeration.",
              "Gaining and Maintaining Access.",
              "System Hacking Techniques.",
              "Penetration Testing with Kali Linux.",
              "Reporting & Documentation.",
            ],
          },
          {
            month: 6,
            heading: "Security Policies, Incident Response & Capstone Project",
            goals: [
              "Learn how organizations manage, detect, and respond to security incidents.",
              "Apply cybersecurity knowledge to a real-world scenario.",
            ],
            tasks: [
              "Design a company-level security policy.",
              "Create an incident response plan.",
              "Conduct a full vulnerability analysis.",
              "Prepare project documentation & presentation.",
              "Final project presentation & review.",
            ],
            topicsCovered: [
              "Security Policies & Compliance Standards (ISO 27001, GDPR).",
              "Risk Assessment and Threat Modeling.",
              "Incident Response and Forensics Basics.",
              "Data Privacy and Backup Management.",
              "Malware Analysis Overview.",
              "Cybersecurity in Cloud & IoT Environments.",
              "Capstone Project Ideas: Network Security Implementation, Web App Penetration Testing, Simulated Cyber Attack & Response, Security Awareness Program, Vulnerability Assessment of a Demo Network.",
            ],
          },
        ],
      },
      {
      id: "adobe-photoshop",
      title: "Adobe Photoshop",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "1 Month",
      icon: "https://www.clipartmax.com/png/middle/419-4192029_adobe-photoshop-logo-svg-png-icon-free-download-photoshop-logo-black-and.png",
      months: [
        {
          month: 1,
          heading: "Adobe Photoshop Training",
          goals: [
            "Build a strong understanding of Photoshop tools and workspace.",
            "Learn professional photo editing, color correction, and image manipulation techniques.",
          ],
          tasks: [
            "Practice photo retouching using Healing and Spot Healing Brush tools.",
            "Perform color correction and adjustments to improve image quality.",
            "Crop, trim, and cut objects using selection tools like Lasso, Object Selection, and Magic Wand.",
            "Work on branding and advertising projects such as logos, posters, and packaging.",
          ],
          topicsCovered: [
            "Introduction to Adobe Photoshop interface and workspace",
            "Photo retouching using Healing and Spot Healing Brush tools",
            "Color correction and enhancement techniques",
            "Cropping, trimming, and object extraction",
            "Using Lasso, Object Selection, and Magic Wand tools",
            "Layer management and image composition",
            "Logo creation and branding concepts",
            "Mockup and packaging design",
            "Promotional poster and brochure design",
            "Advertisement and flyer creation",
          ],
        },
        {
          month: 2,
          heading: "This is a one month internship !",
          goals: ["No Data Available"],
          tasks: ["No Data Available"],
          topicsCovered: [
            "No Data Available",
          ],
        },
       {
          month: 3,
          heading: "This is a one month internship !",
          goals: ["No Data Available"],
          tasks: ["No Data Available"],
          topicsCovered: [
            "No Data Available",
          ],
        },
      ],
    },
    {
      id: "adobe-indesign",
      title: "Adobe indesign",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "1 Month",
      icon: "https://cdn.creazilla.com/icons/3243727/adobe-indesign-icon-size_512.png",
      months: [
        {
          month: 1,
          heading: "Adobe InDesign Essentials",
          goals: [
            "Develop foundational knowledge of Adobe InDesign tools and workspace.",
            "Understand document setup, layout design, and print preparation.",
          ],
          tasks: [
            "Learn and practice core InDesign tools (frames, text wrap, layout basics).",
            "Apply bleed settings and export files for print-ready documents.",
            "Complete project-based tasks such as magazine and portfolio creation.",
          ],
          topicsCovered: [
            "Introduction to Adobe InDesign Interface",
            "Working with Frames and Text Wrap",
            "Understanding Page Layouts and Grids",
            "Applying Bleed and Margins for Print",
            "Exporting Print-Ready Documents (PDF, PNG, etc.)",
            "Typography and Paragraph Styling",
            "Using Master Pages and Templates",
            "Color Management and Swatches",
            "Magazine Design Project",
            "Portfolio Design Project",
          ],
        },
        {
          month: 2,
          heading: "This is a one month internship !",
          goals: ["No Data Available"],
          tasks: ["No Data Available"],
          topicsCovered: [
            "No Data Available",
          ],
        },
       {
          month: 3,
          heading: "This is a one month internship !",
          goals: ["No Data Available"],
          tasks: ["No Data Available"],
          topicsCovered: [
            "No Data Available",
          ],
        },
      ],
    },
    {
      id: "adobe-illustrator",
      title: "Adobe illustrator",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "1 Month",
      icon: "https://cdn-icons-png.flaticon.com/512/2496/2496692.png",
      months: [
        {
          month: 1,
          heading: "Adobe Illustrator Training",
          goals: [
            "Develop a strong foundation in Adobe Illustrator tools and techniques.",
            "Learn to create professional vector-based designs and branding assets.",
          ],
          tasks: [
            "Understand basic tools like shapes, gradients, and brushes.",
            "Master the Pen tool and its applications in professional design.",
            "Create vector illustrations using both Shape and Pen tools.",
            "Design logos, letterheads, business cards, and other brand materials.",
          ],
          topicsCovered: [
            "Introduction to Adobe Illustrator interface and tools",
            "Creation of basic shapes and text manipulation",
            "Use of gradients and brush tools",
            "Pen tool techniques and variations",
            "Vector illustration (beginner to advanced)",
            "Logo design fundamentals and types of logos",
            "Designing letterheads and business cards",
            "Creating ID cards and branding mockups",
            "Project-based design workflows",
            "Final project and portfolio preparation",
          ],
        },
        {
          month: 2,
          heading: "This is a one month internship !",
          goals: ["No Data Available"],
          tasks: ["No Data Available"],
          topicsCovered: [
            "No Data Available",
          ],
        },
       {
          month: 3,
          heading: "This is a one month internship !",
          goals: ["No Data Available"],
          tasks: ["No Data Available"],
          topicsCovered: [
            "No Data Available",
          ],
        },
      ],
    },

    {
      id: "react-js",
      title: "React.js Frontend Development Internship",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
      months: [
        {
          month: 2,
          heading: "Foundation of Frontend Development",
          goals: [
            "Build a strong understanding of core web development technologies.",
            "Develop responsive and accessible web pages using HTML, CSS, and JavaScript.",
          ],
          tasks: [
            "Create personal portfolio and responsive layouts.",
            "Implement interactive UI elements using JavaScript.",
            "Work on exercises to strengthen CSS Flexbox, Grid, and media queries.",
            "Build small web components for practice.",
          ],
          topicsCovered: [
            "Web Development Basics (Structure, Frontend-Backend Overview)",
            "HTML5: Semantic Elements, Forms, Tables, Attributes",
            "CSS3: Styling, Animations, Flexbox, Grid, Responsive Design",
            "JavaScript Fundamentals: Variables, Loops, Functions, Arrays, Objects",
            "DOM Manipulation & Event Handling",
            "Version Control with Git & GitHub",
            "Mini Project: Build a Personal Portfolio Website",
          ],
        },
        {
          month: 4,
          heading: "React.js Development & Component Architecture",
          goals: [
            "Learn to build modern, dynamic frontend applications using React.js.",
            "Understand component-based architecture, hooks, and routing in React.",
          ],
          tasks: [
            "Create reusable React components.",
            "Use hooks like useState and useEffect to manage app state.",
            "Implement navigation using React Router.",
            "Develop a small React project like a Task Tracker or To-Do App.",
          ],
          topicsCovered: [
            "Introduction to React & JSX",
            "Components, Props & State",
            "React Hooks: useState, useEffect, useRef",
            "Conditional Rendering & Lists",
            "React Router (Navigation, Nested Routes)",
            "Form Handling & Validation in React",
            "Context API for State Management",
            "Mini Project: Task Manager App / To-Do List",
          ],
        },
        {
          month: 6,
          heading: "Advanced Frontend & Project Deployment",
          goals: [
            "Gain hands-on experience in integrating APIs and managing complex states.",
            "Build and deploy a production-ready React application.",
          ],
          tasks: [
            "Fetch and display data from REST APIs.",
            "Use advanced state management (Redux or Context).",
            "Optimize app performance and manage environment variables.",
            "Deploy full React project to platforms like Vercel or Netlify.",
          ],
          topicsCovered: [
            "Advanced React Patterns (Custom Hooks, Prop Drilling Solutions)",
            "State Management (Redux / Context API)",
            "API Integration using Axios / Fetch",
            "React Performance Optimization & Lazy Loading",
            "Error Handling and Debugging",
            "Responsive & Accessible Design Practices",
            "Deployment (Vercel / Netlify / GitHub Pages)",
            "Capstone Project: Build a Full React Web App with API Integration",
          ],
        },
      ],
    },

    {
      id: "game-dev",
      title: "Game Development Internship",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://cdn-icons-png.flaticon.com/512/6581/6581038.png",
      months: [
        {
          month: 2,
          heading: "Foundation of Game Development",
          goals: [
            "Understand the fundamentals of game design and development workflow.",
            "Gain practical knowledge of Unity/Unreal Engine and basic programming logic.",
          ],
          tasks: [
            "Set up the development environment (Unity or Unreal).",
            "Create basic 2D and 3D scenes.",
            "Learn to use physics, lighting, and input systems.",
            "Build a simple playable mini-game prototype.",
          ],
          topicsCovered: [
            "Introduction to Game Engines (Unity / Unreal)",
            "Game Design Principles & Pipeline Overview",
            "C# Programming Basics for Game Development",
            "Working with GameObjects & Components",
            "2D vs 3D Game Concepts",
            "Physics, Collisions & Rigidbodies",
            "Basic Animation & Lighting Setup",
            "Camera Controls & User Interaction",
            "Mini Project: 2D Platformer or Endless Runner Game",
          ],
        },
        {
          month: 4,
          heading: "Intermediate Gameplay & Mechanics Development",
          goals: [
            "Develop interactive gameplay mechanics and design engaging levels.",
            "Implement core features such as UI, player controls, and enemy AI.",
          ],
          tasks: [
            "Design levels and integrate environment assets.",
            "Implement player movement, attack systems, and score tracking.",
            "Add sound effects, particle effects, and background music.",
            "Work on an interactive mini-project with game logic and menus.",
          ],
          topicsCovered: [
            "Level Design & Scene Management",
            "Input Systems & Player Controls",
            "UI Design (Menus, HUD, Scoreboards)",
            "Audio Integration (Music, SFX, Ambient Sounds)",
            "Basic AI Programming (Enemy Behavior, Pathfinding)",
            "Animation Controllers & Transitions",
            "Prefabs and Object Pooling",
            "Mini Project: Build a Top-Down Shooter or 3D Maze Game",
          ],
        },
        {
          month: 6,
          heading: "Advanced Game Development & Final Project",
          goals: [
            "Learn optimization, multiplayer concepts, and game deployment.",
            "Build and publish a fully functional 2D/3D game as a capstone project.",
          ],
          tasks: [
            "Integrate advanced game mechanics and visual effects.",
            "Optimize performance for mobile or desktop.",
            "Implement saving/loading systems and in-game economy.",
            "Deploy the final project and present it as a portfolio piece.",
          ],
          topicsCovered: [
            "Game Optimization Techniques (Performance, Memory, Assets)",
            "Lighting, Shaders, and Post-Processing Effects",
            "Multiplayer Basics (Photon / Netcode for Unity)",
            "Saving and Loading Game Data",
            "In-Game Monetization (Ads, Purchases)",
            "Publishing to Platforms (itch.io, Play Store, Steam)",
            "Capstone Project: Complete Game Design, Development & Deployment",
          ],
        },
      ],
    },

    {
      id: "digital-marketing",
      title: "Digital Marketing",
      mode: "Remote/Onsite",
      type: "Internship",
      duration: "6 Months",
      icon: "https://www.kindpng.com/picc/m/75-755692_digital-marketing-icon-black-png-download-marketing-icon.png",
      months: [
        {
          month: 2,
          heading: "Foundation Setup",
          goals: [
            "Define clear marketing goals and identify target audiences.",
            "Establish a strong foundation for brand presence and digital strategy.",
          ],
          tasks: [
            "Set SMART goals (leads, sales, awareness).",
            "Build customer personas: demographics, pain points & behavior.",
            "Analyze competitors’ websites, SEO, ads, and social media.",
            "Identify industry trends and opportunities.",
            "Build a mobile-first, secure, SEO-friendly website.",
            "Set up analytics tools like GA4 and Google Tag Manager.",
            "Develop brand voice, tone, and value proposition.",
          ],
          topicsCovered: [
            "SMART Goal Setting",
            "Customer Persona Development",
            "Competitive & Market Research",
            "SEO-friendly Website Development",
            "Google Analytics 4 (GA4) Setup",
            "Google Tag Manager Integration",
            "Brand Messaging & Visual Identity",
          ],
        },
        {
          month: 4,
          heading: "Traffic Acquisition",
          goals: [
            "Drive website traffic through SEO, content, and social media.",
            "Establish consistent inbound marketing systems.",
          ],
          tasks: [
            "Optimize website with on-page, technical, and off-page SEO.",
            "Start a blog with keyword-rich, evergreen content.",
            "Create lead magnets like eBooks and webinars.",
            "Develop social media strategy and posting schedule.",
            "Build and segment an email list for marketing automation.",
            "Launch and manage paid ad campaigns (Google, Meta).",
          ],
          topicsCovered: [
            "On-page & Technical SEO",
            "Content Marketing Strategy",
            "Lead Magnet Creation",
            "Social Media Marketing (LinkedIn, Instagram, etc.)",
            "Email Marketing Automation",
            "PPC Campaign Management (Google Ads, Meta Ads)",
          ],
        },
        {
          month: 6,
          heading: "Conversion, Scaling & Authority Building",
          goals: [
            "Optimize for conversions and scale campaigns efficiently.",
            "Establish authority and long-term brand sustainability.",
          ],
          tasks: [
            "Perform Conversion Rate Optimization (CRO) with A/B testing.",
            "Implement advanced analytics and heatmaps for performance tracking.",
            "Automate marketing workflows and segment audiences.",
            "Collaborate with influencers and run affiliate programs.",
            "Publish thought leadership content (guest posts, podcasts).",
            "Build online communities and expand ad reach.",
            "Plan for global and multichannel marketing strategy.",
          ],
          topicsCovered: [
            "Conversion Rate Optimization (CRO)",
            "Advanced Analytics & Data Tracking",
            "Marketing Automation & CRM",
            "Influencer & Affiliate Marketing",
            "Thought Leadership & Content Authority",
            "Community Building & Engagement",
            "Scaling Paid Ads & Global Marketing Strategy",
          ],
        },
      ],
    },
  ],
};

export default internshipDetailData;
  